### ISSUE TITLE
中文名的文件无法打开

### ISSUE THREAD

**Issue by ezleeinfo** [ethendev/wopihost#1]
不知道是哪里的编码问题，中文名文件无法打开

**Comment by ethendev** [comment]
将中文名称编码后存储。

在 2018-02-07 11:22:23，ezleeinfo <notifications@github.com> 写道：


不知道是哪里的编码文件，中文名文件无法打开

**Comment by huminted** [comment]
文件中文名无法预览。请赐教详细解决办法

**Comment by ethendev** [comment]
@ezleeinfo @huminted 中文名可以正常预览，解决方案请看README.md中的常见问题说明。
