### ISSUE TITLE
请教一下，关于Lock的问题

### ISSUE THREAD

**Issue by dahai118y** [ethendev/wopihost#12]
关于Lock的使用，我实在是有点晕。
可以简单讲讲吗？感谢

**Comment by ethendev** [comment]
> 关于Lock的使用，我实在是有点晕。
> 可以简单讲讲吗？感谢

wopi协议里有个与锁有关的接口
```
    @PostMapping("/files/{name}")
    public ResponseEntity handleLock(@PathVariable(name = "name") String name, HttpServletRequest request) {
        return wopiHostService.handleLock(name, request);
    }
```

与锁有关的操作有获取锁，加锁，刷新锁，解锁。我的代码中已经实现了这4个操作。在编辑文件的时候，office会调用上面的接口去获取锁，然后对文件加锁。如果加锁成功，就可以对文件进行编辑操作，加锁失败则不能编辑。刷新锁操作通过将文件的自动到期计时器重置为30分钟来刷新文件上的锁，之后会进行解锁。
