### ISSUE TITLE
求助！WOPISrc使用HTTPS协议不能预览Excel文稿

### ISSUE THREAD

**Issue by dahai118y** [ethendev/wopihost#13]
请问如何支持文稿源是一个HTTPS的协议？现在不能打开文稿了。
在官网看CertificateName这个看起来不像啊？

**Comment by ethendev** [comment]
> 请问如何支持文稿源是一个HTTPS的协议？现在不能打开文稿了。
> 在官网看CertificateName这个看起来不像啊？

CertificateName: 指定 Office Online Server 用于创建 HTTPS 绑定的证书的名称。[参数说明](https://docs.microsoft.com/zh-cn/powershell/module/officewebapps/new-officewebappsfarm?view=officewebapps-ps)

你试下wopi和 Office Online Server 服务器能不能相互 ping 通。

**Comment by dahai118y** [comment]
> > 请问如何支持文稿源是一个HTTPS的协议？现在不能打开文稿了。
> > 在官网看CertificateName这个看起来不像啊？
> 
> CertificateName: 指定 Office Online Server 用于创建 HTTPS 绑定的证书的名称。[参数说明](https://docs.microsoft.com/zh-cn/powershell/module/officewebapps/new-officewebappsfarm?view=officewebapps-ps)
> 
> 你试下wopi和 Office Online Server 服务器能不能相互 ping 通。

我妥协了。我把wopi的服务换成了http了。
请求office server的时候用/op/view.aspx?src=https://***.com/***.xlsx没问题了。
但是用/x/_layouts/xlviewerinternal.aspx?edit=1&WOPISrc=https://***.com/***.xlsx还是不行

**Comment by ethendev** [comment]
@dahai118y 我之前用的也是HTTP协议，没用过HTTPS。我在微软官网上看到https相关的配置，但是我现在没有环境了，测试不了。如果你有兴趣的话可以照着配了试试。
https://docs.microsoft.com/zh-cn/powershell/module/sharepoint-server/set-spwopizone?view=sharepoint-ps
