### ISSUE TITLE
xlsx无法在线预览，但是在线编辑正常

### ISSUE THREAD

**Issue by 260645256** [ethendev/wopihost#14]
您好，使用x/_layouts/xlviewerinternal.aspx?ui=zh-CN&rs=zh-CN&WOPISrc=此地址无法正常预览xlsx文件
![image](https://user-images.githubusercontent.com/37361266/100320476-2db47f80-2ffc-11eb-8fe5-2e5ed4a24321.png)
但是在线编辑是可以正常使用的，请问这有办法解决吗，谢谢！

**Comment by ethendev** [comment]
> 您好，使用x/_layouts/xlviewerinternal.aspx?ui=zh-CN&rs=zh-CN&WOPISrc=此地址无法正常预览xlsx文件
> ![image](https://user-images.githubusercontent.com/37361266/100320476-2db47f80-2ffc-11eb-8fe5-2e5ed4a24321.png)
> 但是在线编辑是可以正常使用的，请问这有办法解决吗，谢谢！

抱歉这几天没看邮件。你可以把getFileInfo方法中的`info.setSha256(getHash256(file));`这一行代码注释掉看看呢

**Comment by 260645256** [comment]
已试过，没有效果，暂时用别的办法替代xlsx文件的预览了，谢谢哈
