### ISSUE TITLE
编辑页面可以打开，但是查看页面打不开

### ISSUE THREAD

**Issue by openmartin** [ethendev/wopihost#2]
Word 编辑的的页面可以打开，但是查看的页面打不开，请问您遇到过这个问题么？

**Comment by ethendev** [comment]
你检查一下是不是请求路径没写对。如果其他格式的文件也存在这个问题，那有可能是office online server有问题，建议重新安装试试。

**Comment by openmartin** [comment]
解决了：CheckFileInfo 返回的 json 中 去掉 SHA256 就可以查看了，而且也不影响编辑
