### ISSUE TITLE
你好，可以认识一下吗？

### ISSUE THREAD

**Issue by 951240778** [ethendev/wopihost#3]
你好，我看到你的帖子，过来向您请教一下office  webapp 的一些问题，今天我刚把服务器搭建好了，就是不知道如何 怎么在线预览文件

**Comment by 951240778** [comment]
希望加个qq：951240778

**Comment by ethendev** [comment]
@951240778 
抱歉回复晚了， [教程](https://blog.csdn.net/yufeiyanliu/article/details/70226769)  最下方的参考资料里面有详细的 office online 安装、配置教程，你可以先试着自己配置。如果使用过程中碰到问题再讨论。

**Comment by 951240778** [comment]
哎，没搞定。
