### ISSUE TITLE
  word文档可以编辑，但是不能插入图片

### ISSUE THREAD

**Issue by sarmnoo** [ethendev/wopihost#4]
您好，我尝试跑了一下您的代码，word可以预览和编辑(打字可以)，但是插入图片的按钮是灰的，不能插入图片，所以想请问一下是什么原因？

**Comment by ethendev** [comment]
@sarmnoo 这个问题我没有碰到过。你打开浏览器控制台看看office有没有报错信息，或者看office日志。默认路径  %programdata%\Microsoft\OfficeWebApps\Data\Logs\ULS\。

**Comment by ztwz** [comment]
我在编辑word文章的时候，有时候保存成功后，会把光标前或后的内容重复多次插入光标处，请问有遇到这问题吗？

**Comment by ethendev** [comment]
@ztwz 可以检查一下保存的时候是否有其他人在同时操作这个文件。如果是这种情况，可以参考下面的文章加锁。
https://wopi.readthedocs.io/projects/wopirest/en/latest/files/PutFile.html

**Comment by ztwz** [comment]
没有，就我一人在操作，我在开发环境做测试出现在这问题的，出现几率很高。
[如图:]  http://47.101.151.193:8099/20190306.png 
重复了9次，多了9个问号。 @ethendev

**Comment by ethendev** [comment]
@ztwz 这个问题我没有碰到过，你可以在微软的GitHub上问一下。
https://github.com/Microsoft/Office-Online-Test-Tools-and-Documentation
