### ISSUE TITLE
可以预览，但无法编辑

### ISSUE THREAD

**Issue by downleave** [ethendev/wopihost#5]
docx，预览是正常的，但到编辑页时，显示“抱歉，您无权编辑此文档”，不知道您是否有遇到过相似问题。

**Comment by downleave** [comment]
解决了，少了"UserCanWrite":true这个参数，其实我是PHP写的，谢谢参考了，哈哈

**Comment by wuqinqiang** [comment]
> 解决了，少了"UserCanWrite":true这个参数，其实我是PHP写的，谢谢参考了，哈哈

老哥这个参数是加在哪里的，能否给个参照

**Comment by downleave** [comment]
> > 解决了，少了"UserCanWrite":true这个参数，其实我是PHP写的，谢谢参考了，哈哈
> 
> 老哥这个参数是加在哪里的，能否给个参照

是写在fileInfo那个方法里面的

**Comment by wuqinqiang** [comment]
> > > 解决了，少了"UserCanWrite":true这个参数，其实我是PHP写的，谢谢参考了，哈哈
> > 
> > 
> > 老哥这个参数是加在哪里的，能否给个参照
> 
> 是写在fileInfo那个方法里面的

因为我也是在用php实现，麻烦一下老哥再问一个问题，不知道你是否遇到过，我在查看pptx和docx文件没有问题，但是当我打开execl文件显示很抱歉，无法打开您的工作薄，一开始以为是文件的问题，但是换了几个文件也这样，这方面google资料太少了，请问你知道原因吗？谢谢

**Comment by downleave** [comment]
这个我就不清楚了，我只用过docx

**Comment by ethendev** [comment]
@wuqinqiang 如果只有execl有问题（非格式问题），其他都正常，有可能是 office online 的Excel没有安装正确。我以前碰到过类似的情况，你可以使用新的服务器或者虚拟机重新安装试一下。

**Comment by downleave** [comment]
@ethendev @wuqinqiang 我也借此问下大佬，有没有搞过office online server的加载项？我现在是加载项按钮出来了，但不知如何让它加载自己开发的加载项。而我们开发的加载项不打算上线，只需要在本地加载。目前查到的资料是无法使用类似office365的集中部署。客户端的“共享文件夹”加载似乎也不可行。

**Comment by wuqinqiang** [comment]
> @ethendev @wuqinqiang 我也借此问下大佬，有没有搞过office online server的加载项？我现在是加载项按钮出来了，但不知如何让它加载自己开发的加载项。而我们开发的加载项不打算上线，只需要在本地加载。目前查到的资料是无法使用类似office365的集中部署。客户端的“共享文件夹”加载似乎也不可行。

暂时还没搞那个，接触了两天这个，准备做编辑的时候发现不能读取execl的情况，我单独把它从我的系统拿出来测试又是可以的，那应该就不是安装的问题了，你们有安装sharepoint来调用office web apps服务吗。我是没安装的。

**Comment by cheakin** [comment]
> @ethendev @wuqinqiang我也可以问下大佬，有没有搞过办公室在线服务器的加载项？我现在是加载项按钮出来了，但不知如何让它加载自己开发的加载项。而我们开发的加载项不打算上线，只需要在本地加载。目前查到的资料是无法使用类似office365的集中部署。客户端的“共享文件夹”加载似乎也不可行。

在office online server 中运行Set-OfficeWebAppsFarm - OfficeAddinEnabled:$true
