### ISSUE TITLE
是否可以保存到服务器

### ISSUE THREAD

**Issue by sendsnow** [ethendev/wopihost#6]
请问作者，当对ppt进行预览，编辑，保存的时候，是否可以把编辑过后的ppt保存到服务器

**Comment by ethendev** [comment]
@sendsnow 目前文件是直接存储在部署wopihost的服务器上，如果你想把编辑后的文件存储在其他服务器上，你可以修改controller中的接口实现啊。

**Comment by dahai118y** [comment]
> @sendsnow 目前文件是直接存储在部署wopihost的服务器上，如果你想把编辑后的文件存储在其他服务器上，你可以修改controller中的接口实现啊。

我发现是要隔2分钟左右才会同步，这个可以做到实时同步，或者自己定义时间吗？

**Comment by ethendev** [comment]
> > @sendsnow 目前文件是直接存储在部署wopihost的服务器上，如果你想把编辑后的文件存储在其他服务器上，你可以修改controller中的接口实现啊。
> 
> 我发现是要隔2分钟左右才会同步，这个可以做到实时同步，或者自己定义时间吗？

WOPI服务器不能影响自动保存发生的频率。并且不同文档之间可能频率不一样。
Word 每30秒保存一次，Excel  每2分钟保存一次，PowerPoint 每60秒保存一次。
