### ISSUE TITLE
编辑word 服务器错误

### ISSUE THREAD

**Issue by vickllny** [ethendev/wopihost#7]
在编辑word的时候 提示=服务器错误，以下：
服务器错误
很抱歉，发生错误。
我们已经为服务器管理员记录了错误。

在
http://win-218dfg3hi4l.ad.com/op/generate.aspx# 上输入我的文件地址，复制预览地址，能预览文件。
但是在 http://win-218dfg3hi4l.ad.com/wv/wordviewerframe.aspx? WOPISrc=文件地址  就报了以上错误。您有好的建议去排查问题吗

**Comment by ethendev** [comment]
@vickllny 
可以这样去检查下问题啊
1. 安装 office online server 的服务器和 wopihost 的服务器需要配置域控
2. wopihost 能否访问到你的文件

**Comment by vickllny** [comment]
能访问到呢。
http://win-218dfg3hi4l.ad.com/op/view.aspx?src=我的文件地址  能预览

**Comment by vickllny** [comment]
ok. 解决了。用的你的工程代码做的。
我发现我的问题就是没有去实现wopi协议。感谢。
你的controller拼写错误 😝
