### ISSUE TITLE
Edit in browser

### ISSUE THREAD

**Issue by HSan88** [ethendev/wopihost#9]
please add "Edit in browser "
now this option is not enabled, 
at least tell me know how to enable this option. of course I know for enabling this button we have to set this properties (UserCanWrite, HostEditUrl, HostViewUrl, EditModePostMessage) but it doesn't work. 
please help

**Comment by ethendev** [comment]
@HSan88 
You need to make sure **SupportsUpdate** and **UserCanWrite** are set to true.
Wopi only supports editing a few specific formats. For example, **.doc** is not supported.

**Comment by HSan88** [comment]
@ethendev 
Thank you for your response
both of those properties are true, Edit in browser button is enable but, when in I click it, it doesn't redirect to edit url. of course I use for docx format.

**Comment by ethendev** [comment]
@HSan88 
I think there is something wrong with your office online server configuration. You can refer to [office installation guide](https://docs.microsoft.com/en-us/officeonlineserver/deploy-office-online-server?redirectedfrom=MSDN) to check whether the configuration is correct.
